# This is a basic workflow to help you get started with Actions
 parihar1302-patch-1

=======
 featuring
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.cc080bc45844b598798e5f1cae1f537c1b45feb2}}
        SONAR_TOKEN: ${{ secrets.2102c96971a22812e1f821692b06b6737c14f8e4 }}
